font_family JetBrainsMono Nerd Font
font_size 11.5
bold_font auto
italic_font auto
bold_italic_font auto
symbol_map U+E000-U+F8FF Symbols Nerd Font Mono
symbol_map U+1F300-U+1FAFF Noto Color Emoji

enable_ligatures yes

disable_ligatures never
# url_color #61afef

cursor_shape block
cursor_stop_blinking_after 0
scrollback_lines 2000
copy_on_select yes
mouse_hide_wait 0
select_by_word_characters @-./_~?&=%+#a
enable_audio_bell no
bell_on_tab "🔔 "
remember_window_size  no
window_border_width 1pt
draw_minimal_borders yes
window_padding_width 10
inactive_text_alpha 0.6
hide_window_decorations yes
confirm_os_window_close 0
tab_bar_style powerline
background_opacity 0.95

# --- Triple Buffer (Múltiples Clipboards) ---
# Fila de números para GUARDAR (Ctrl + Shift + 1, 2, 3)
map f1 copy_to_buffer a
map f3 copy_to_buffer b
map f5 copy_to_buffer c
# Fila QWE para PEGAR (Ctrl + Shift + Q, W, E)
map f2 paste_from_buffer a
map f4 paste_from_buffer b
map f6 paste_from_buffer c

# BEGIN_KITTY_THEME
# Emilia
include current-theme.conf
# END_KITTY_THEME
